// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package server

import (
	"context"

	"bolg/rpc/article/article_client"
	"bolg/rpc/article/internal/logic"
	"bolg/rpc/article/internal/svc"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	article_client.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) AddArticle(ctx context.Context, in *article_client.AddArticleRequest) (*article_client.ArticleList, error) {
	l := logic.NewAddArticleLogic(ctx, s.svcCtx)
	return l.AddArticle(in)
}

func (s *ArticleServer) GetArticle(ctx context.Context, in *article_client.GetArticleRequest) (*article_client.ArticleList, error) {
	l := logic.NewGetArticleLogic(ctx, s.svcCtx)
	return l.GetArticle(in)
}

func (s *ArticleServer) UpdateArticle(ctx context.Context, in *article_client.UpdateArticleRequest) (*article_client.ArticleList, error) {
	l := logic.NewUpdateArticleLogic(ctx, s.svcCtx)
	return l.UpdateArticle(in)
}

func (s *ArticleServer) DeleteArticle(ctx context.Context, in *article_client.DeleteArticleRequest) (*article_client.ArticleList, error) {
	l := logic.NewDeleteArticleLogic(ctx, s.svcCtx)
	return l.DeleteArticle(in)
}
