// Code generated by goctl. DO NOT EDIT.
// Source: classify.proto

package server

import (
	"context"

	"bolg/rpc/classify/classify_client"
	"bolg/rpc/classify/internal/logic"
	"bolg/rpc/classify/internal/svc"
)

type ClassifyServer struct {
	svcCtx *svc.ServiceContext
	classify_client.UnimplementedClassifyServer
}

func NewClassifyServer(svcCtx *svc.ServiceContext) *ClassifyServer {
	return &ClassifyServer{
		svcCtx: svcCtx,
	}
}

func (s *ClassifyServer) AddClassify(ctx context.Context, in *classify_client.AddClassifyRequest) (*classify_client.ClassifyList, error) {
	l := logic.NewAddClassifyLogic(ctx, s.svcCtx)
	return l.AddClassify(in)
}

func (s *ClassifyServer) GetClassify(ctx context.Context, in *classify_client.GetClassifyRequest) (*classify_client.ClassifyList, error) {
	l := logic.NewGetClassifyLogic(ctx, s.svcCtx)
	return l.GetClassify(in)
}

func (s *ClassifyServer) GetAllClassify(ctx context.Context, in *classify_client.GetAllClassifyRequest) (*classify_client.ClassifyList, error) {
	l := logic.NewGetAllClassifyLogic(ctx, s.svcCtx)
	return l.GetAllClassify(in)
}

func (s *ClassifyServer) UpdateClassify(ctx context.Context, in *classify_client.UpdateClassifyRequest) (*classify_client.ClassifyList, error) {
	l := logic.NewUpdateClassifyLogic(ctx, s.svcCtx)
	return l.UpdateClassify(in)
}

func (s *ClassifyServer) DeleteClassify(ctx context.Context, in *classify_client.DeleteClassifyRequest) (*classify_client.ClassifyList, error) {
	l := logic.NewDeleteClassifyLogic(ctx, s.svcCtx)
	return l.DeleteClassify(in)
}
