// Code generated by goctl. DO NOT EDIT.
package types

type MenuRespose struct {
	Code    uint16      `json:"code"`
	Data    []*MenuData `json:"data"`
	Message string      `json:"message"`
}

type MenuData struct {
	ID       uint64      `json:"id,optional"`
	ParentId *uint64     `json:"parentId,optional"`
	Order    uint32      `json:"order"`
	Title    string      `json:"title"`
	Icon     string      `json:"icon"`
	Url      string      `json:"url"`
	Disabled uint32      `json:"disabled"`
	Hide     bool        `json:"hide"`
	Children []*MenuData `json:"children,optional"`
}

type GetMenutReq struct {
}

type UpdateMenuReq struct {
	Data []*MenuData `json:"data"`
}

type DeleteMenuReq struct {
	ID uint64 `path:"id"`
}

type AddMenuReq struct {
	Data []*MenuData `json:"data"`
}

type ArticleRespose struct {
	Code    uint16         `json:"code"`
	Data    []*ArticleData `json:"data"`
	Message string         `json:"message"`
}

type AddArticleReq struct {
	Title       string   `json:"title"`
	Content     string   `json:"content"`
	Status      uint32   `json:"status"`
	Draft       bool     `json:"draft,default=1"`
	ClassifyIds []uint64 `json:"classifyIds,optional,default=[]"`
}

type GetArticleReq struct {
	ID uint64 `path:"id"`
}

type GetArticleByPagingReq struct {
	PageSize uint32 `form:"pageSize"`
	PageNum  uint32 `form:"pageNum"`
	Draft    *bool  `form:"draft,optional"`
}

type UpdateArticleReq struct {
	Id          uint64   `path:"id"`
	Title       string   `json:"title"`
	Content     string   `json:"content"`
	Status      uint32   `json:"status"`
	Draft       bool     `json:"draft,default=1"`
	ClassifyIds []uint64 `json:"classifyIds,optional,default=[]"`
}

type DeleteArticleReq struct {
	ID uint64 `path:"id"`
}

type ArticleData struct {
	ID           uint64                 `json:"id"`
	Title        string                 `json:"title"`
	Content      string                 `json:"content"`
	CreateAt     int64                  `json:"createAt"`
	UpdateAt     int64                  `json:"updateAt"`
	DeleteAt     int64                  `json:"deleteAt"`
	Status       uint32                 `json:"status"`
	Draft        bool                   `json:"draft,default=1"`
	ClassifyData []*ArticleClassifyData `json:"classifyData,optional"`
}

type ArticleClassifyData struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
	Icon string `json:"icon"`
}

type ClassifyRespose struct {
	Code    uint16          `json:"code"`
	Data    []*ClassifyData `json:"data"`
	Message string          `json:"message"`
}

type AddClassifyReq struct {
	Name       string   `json:"name"`
	Icon       string   `json:"icon"`
	ArticleIds []uint64 `json:"articleIds,optional,default=[]"`
}

type ClassifyData struct {
	ID          uint64                 `json:"id"`
	Name        string                 `json:"name"`
	CreateAt    int64                  `json:"createAt"`
	UpdateAt    int64                  `json:"updateAt"`
	Icon        string                 `json:"icon"`
	ArticleData []*ClassifyArticleData `json:"articleData,optional"`
}

type GetClassifyReq struct {
	ID int64 `path:"id"`
}

type UpdateClassifyReq struct {
	ID          uint64   `path:"id"`
	Name        string   `json:"name"`
	Icon        string   `json:"icon"`
	ArticlesIds []uint64 `json:"articleIds"`
}

type DeleteClassifyReq struct {
	ID uint64 `path:"id"`
}

type ClassifyArticleData struct {
	ID       uint64 `json:"id"`
	Title    string `json:"title"`
	Content  string `json:"content"`
	Draft    bool   `json:"draft"`
	UpdateAt int64  `json:"updateAt"`
	Status   uint32 `json:"status"`
}
