// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	article "bolg/src/article/api/internal/handler/article"
	"bolg/src/article/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: article.AddArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: article.GetArticleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/article"),
	)
}
