// Code generated by goctl. DO NOT EDIT.
package types

type AddReq struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Status   uint   `json:"status"`
	Classify string `json:"classify"`
	Comment  string `json:"comment"`
}

type ArticleData struct {
	ID           uint           `json:"id"`
	Title        string         `json:"title"`
	Content      string         `json:"content"`
	CreateAt     int64          `json:"createAt"`
	UpdateAt     int64          `json:"updateAt"`
	DeleteAt     int64          `json:"deleteAt"`
	Status       uint           `json:"status"`
	ClassifyData []ClassifyData `json:"classifyData"`
	CommentID    CommentID      `json:"commentID"`
}

type CommentID struct {
	CommentID []uint `json:"commentID"`
}

type ClassifyData struct {
	ID   uint   `json:"id"`
	Name string `json:"name"`
	Icon string `json:"icon"`
}

type GetReq struct {
	ID uint `path:"id"`
}
