// Code generated by goctl. DO NOT EDIT.
// Source: base.proto

package server

import (
	"context"

	"bolg/rpc/base/base_client"
	"bolg/rpc/base/internal/logic"
	"bolg/rpc/base/internal/svc"
)

type BaseServer struct {
	svcCtx *svc.ServiceContext
	base_client.UnimplementedBaseServer
}

func NewBaseServer(svcCtx *svc.ServiceContext) *BaseServer {
	return &BaseServer{
		svcCtx: svcCtx,
	}
}

func (s *BaseServer) AddMenu(ctx context.Context, in *base_client.MenuListResponse) (*base_client.MenuListResponse, error) {
	l := logic.NewAddMenuLogic(ctx, s.svcCtx)
	return l.AddMenu(in)
}

func (s *BaseServer) GetMenu(ctx context.Context, in *base_client.GetMenuRequest) (*base_client.MenuListResponse, error) {
	l := logic.NewGetMenuLogic(ctx, s.svcCtx)
	return l.GetMenu(in)
}

func (s *BaseServer) UpdateMenu(ctx context.Context, in *base_client.UpdateMenuRequest) (*base_client.MenuListResponse, error) {
	l := logic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

func (s *BaseServer) DeleteMenu(ctx context.Context, in *base_client.DeleteMenuRequest) (*base_client.MenuListResponse, error) {
	l := logic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}
